version: '3'
# version: '3.8'
# Definimos una aplicación con 2 servicios (microservicios)
services: 
# Servicio 1: apache/php con aplicación CRUD
  apache:
    image: lumigv/lamp-crud-app:1.0
    ports: 
      - 80:80
# Controla el orden inicio de los servicios      
    depends_on:
      - mariadb
# Definimos una política de reinicio del servicio: el contenedor se reinicia cada vez que se detiene por cualquier motivo, excepto cuando se detiene de forma manual (explícita)
# Recomendable en entornos de producción en un único servidor.
    restart: always      

# Servicio 2: mariadb 
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment: 
# El acceso a las variables de entorno puede ser de dos maneras: $MARIADB_DATABASE ó ${MARIADB_DATABASE} utilizan el valor de la variable MARIADB_DATABASE definida en .env
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - LANG=C.UTF-8
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d 
    restart: always

  