name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          docker build -t elbertogamer/actividad61-aplicacion-crud-php:latest .
  
  push_to_dockerhub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push Docker image
        run: |
          docker tag elbertogamer/actividad61-aplicacion-crud-php:latest ${{ secrets.DOCKERHUB_USERNAME }}/elbertogamer/actividad61-aplicacion-crud-php:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/elbertogamer/actividad61-aplicacion-crud-php:latest

  deploy:
    needs: push_to_dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Connect to AWS server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/elbertogamer/actividad61-aplicacion-crud-php:latest
            docker stop actividad61-aplicacion-crud-php || true
            docker rm my-app || true
            docker run -d --name actividad61-aplicacion-crud-php -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/elbertogamer/actividad61-aplicacion-crud-php:latest
